# Generated by Django 3.2.4 on 2021-11-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_remove_bigdata_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigdata',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
